name: Graphino
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  get: 3.12.1
  get_storage: 1.3.1
  animations:
  google_sign_in: 4.5.4
  cloud_firestore:
  firebase_auth:
  firebase_core:
  cupertino_icons: ^0.1.3
  flutter:
    sdk: flutter

dev_dependencies:
  lint:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png